basePath: /
definitions:
  auth.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  auth.LoginResponse:
    properties:
      roles:
        items:
          type: string
        type: array
      token:
        type: string
    type: object
  base.HealthStatus:
    properties:
      goVersion:
        type: string
      memory:
        $ref: '#/definitions/base.MemStats'
      startTime:
        type: string
      status:
        type: string
      uptime:
        type: string
      version:
        type: string
    type: object
  base.MemStats:
    properties:
      alloc:
        type: integer
      heapInUse:
        type: number
      numGC:
        type: integer
      sys:
        type: integer
      totalAlloc:
        type: integer
    type: object
  services.ServiceInfo:
    properties:
      description:
        type: string
      displayName:
        type: string
      name:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: your.email@example.com
    name: Your Name
    url: https://github.com/toxic-development/sysmanix
  description: Cross-platform service management API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://opensource.org/licenses/MIT
  title: SysManix API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
      summary: Authenticate user
      tags:
      - auth
  /health:
    get:
      consumes:
      - application/json
      description: Returns service health information and status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.HealthStatus'
      summary: Get service health
      tags:
      - health
  /services:
    get:
      consumes:
      - application/json
      description: Returns a list of all system services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.ServiceInfo'
            type: array
      security:
      - BearerAuth: []
      summary: List all services
      tags:
      - services
  /services/start/{name}:
    post:
      consumes:
      - application/json
      description: Starts the specified system service
      parameters:
      - description: Service name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Start a service
      tags:
      - services
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and the JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
